FROM centos:centos7.3.1611
USER root

COPY ./fileserver /opt/fileserver

RUN yum install -y --downloadonly --downloaddir=/opt/fileserver/centos-repo createrepo
RUN yum install -y createrepo
RUN createrepo -d /opt/fileserver/centos-repo

WORKDIR /opt/fileserver
RUN chmod 775 /opt/fileserver/startHttp.sh
ENTRYPOINT ["/opt/fileserver/startHttp.sh"]





